name: xintel
description: "Xintel Web"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1

  # call api
  http: ^1.2.2
  graphql: ^5.1.2
  gql: ^1.0.0

  # state management
  get: ^4.6.6

  # preferences
  get_storage: ^2.1.1
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  html_unescape: ^2.0.0
  styled_text: ^8.1.0
  animate_do: ^4.2.0
  flutter_screenutil: ^5.9.3
  any_link_preview: ^3.0.3
  minio: ^3.5.7
  video_player: ^2.10.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  mime: ^2.0.0
  url_launcher: ^6.3.1
  socket_io_client: ^3.1.2
  event_bus: ^2.0.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  
  uses-material-design: true

  assets:
    - .env

    - assets/images/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 800

